type Round =
  | "rounded-none"
  | "rounded-sm"
  | "rounded"
  | "rounded-md"
  | "rounded-lg"
  | "rounded-xl"
  | "rounded-2xl"
  | "rounded-3xl"
  | "rounded-full"
  // side-specific
  | `rounded-t-${
      | "none"
      | "sm"
      | ""
      | "md"
      | "lg"
      | "xl"
      | "2xl"
      | "3xl"
      | "full"}`
  | `rounded-b-${
      | "none"
      | "sm"
      | ""
      | "md"
      | "lg"
      | "xl"
      | "2xl"
      | "3xl"
      | "full"}`
  | `rounded-l-${
      | "none"
      | "sm"
      | ""
      | "md"
      | "lg"
      | "xl"
      | "2xl"
      | "3xl"
      | "full"}`
  | `rounded-r-${
      | "none"
      | "sm"
      | ""
      | "md"
      | "lg"
      | "xl"
      | "2xl"
      | "3xl"
      | "full"}`
  // corner-specific
  | `rounded-tl-${
      | "none"
      | "sm"
      | ""
      | "md"
      | "lg"
      | "xl"
      | "2xl"
      | "3xl"
      | "full"}`
  | `rounded-tr-${
      | "none"
      | "sm"
      | ""
      | "md"
      | "lg"
      | "xl"
      | "2xl"
      | "3xl"
      | "full"}`
  | `rounded-bl-${
      | "none"
      | "sm"
      | ""
      | "md"
      | "lg"
      | "xl"
      | "2xl"
      | "3xl"
      | "full"}`
  | `rounded-br-${
      | "none"
      | "sm"
      | ""
      | "md"
      | "lg"
      | "xl"
      | "2xl"
      | "3xl"
      | "full"}`
  // arbitrary values
  | `rounded-[${string}]`;

export default Round;
